apiVersion: apps/v1
kind: Deployment
metadata:
  name: devguy-deployment
  labels:
    component: devguy
spec:
  replicas: 2
  selector:
    matchLabels:
      component: devguy
  template:
    metadata:
      labels:
        component: devguy
    spec:
      containers:
        - name: devguy
          image: jakethecoder95/devguy:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
