apiVersion: apps/v1
kind: Deployment
metadata:
  name: devguy-deployment
  labels:
    component: devguy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: devguy
  template:
    metadata:
      labels:
        component: devguy
    spec:
      containers:
        - name: devguy
          image: jakethecoder95/devguy:latest
          resources:
            requests:
              cpu: 50m
              memory: 1Mi
              ephemeral-storage: 1Mi
            limits:
              cpu: 100m
              memory: 2Mi
              ephemeral-storage: 2Mi
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
