apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devguy-cluster-ip-service
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: devguy-cluster-ip-service
                port:
                  number: 8080
