name: CI Pipeline
run-name: ${{ github.event.head_commit.message }} - ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.22'
      - name: Build
        working-directory: ./app
        run: go build main.go
