name: CI Pipeline
run-name: ${{ github.event.head_commit.message }} - ${{ github.actor }}

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE: jakethecoder95/devguy

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.22'

      - name: Build
        working-directory: ./app
        run: go build main.go

      - name: Test
        working-directory: ./app
        run: echo "TODO - Write Tests"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Deploy
        run: ./.github/scripts/docker-build.sh
