name: CI Pipeline
run-name: Building "${{ github.event.head_commit.message }}" by {{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.0
      - name: Build
        working-directory: ./app
        run: go build main.go
      - name: Test
        working-directory: ./app
        run: go test
